.TH cwrap.py 1 "February 17, 2012" "version 0.4.1" "USER COMMANDS"
.SH NAME
cwrap.py \- A cron job wrapper used to suppress output
.SH SYNOPSIS
.B cwrap.py [options] (command [cmd-arg [cmd-arg ...]] | 'command [cmd-arg [cmd-arg ...]]')
.SH DESCRIPTION
.nf
/path/to/cwrap.py command --arg1 --arg2
.fi
todo
.PP
section 2
.SH OPTIONS
.TP
\-h
display a short help
.PP
.SH EXIT STATUS
The exit status of this itself should be ignored.  
.SH AUTHOR
Jay Deiman (admin (at) splitstreams.com)
.SH SEE ALSO
cron(8), crontab(1), crontab(5)
